# DOCKER-COMPOSE.YML
# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:8.0
    container_name: fallecido-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: fallecidos_app_db
      MYSQL_USER: funeraria
      MYSQL_PASSWORD: password123
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"